config:
  
  ankle_position_setpoint_radians: 0.0       # set the ankle joint setpoint in radians
  ankle_initial_position_radians:  -0.03 #0.0872665             # set the initial ankle angle in radians
  ankle_initial_velocity: 0.3  # Example: Set initial ankle velocity to 0.2 rad/s

  # # Initial velocities
  foot_rotation_initial_velocity: 0.0
  foot_x_initial_velocity: 0.0
  foot_z_initial_velocity: 0.0
  

  # Hip joint parameters
  hip_position_setpoint_radians: 0.0
  hip_initial_position_radians: 0.0
  hip_initial_velocity: 0.0

  foot_angle_initial_position_radians: 0                # set the initial angle of the foot
  simend: 10                                           # set the duration for which the simulation will run
  M_total: 60                                           # total mass of the human, used for literature estimate calculations
  H_total: 1.59                                         # total height of the human, used for literature estimtae calculations
  mp4_file_name: 'LQR_PDexo_unbalance.mp4'      # file name for mp4 file to be saved to, if you want to record the simultation rendering
  mp4_fps: 60                                           # video fps
  mp4_flag: True                                      # toggle this parameter on / off to save an mp4 video with name "mp4_file_name" (two lines up)
  translation_friction_constant: 0.99                   # set the translationl friction constant for model geoms
  rolling_friction_constant: 0.99                       # set the rolling friction constant for model geoms
  xml_path: 'initial_humanoid.xml'                      # set the file path that the run_sim.py script will read and modify with literature estimates
  lit_xml_file: 'literature_humanoid.xml'               # set file path that run_sim.py will save literature estimate XML file too; this is loaded into the MuJoCo backend
  plotter_flag: False                                 # toggle the Python plotters on / off
  simulation_timestep: 0.0005     #0.0001               # set the simulation timestep - this attribute is critical to simulation success
  visualization_flag: True  # Enable/disable MuJoCo 3D visualization
  visualize_contact_force: False                         # toggle on / off to visualize contact forces
  visualize_perturbation_force: False                    # toggle on / off to visualize perturbation forces
  visualize_joints: False                               # toggle on / off to visualize model joints
  visualize_actuators: False                             # toggle on / off to visualize model actuators
  visualize_center_of_mass: False                       # toggle on / off to visualize humanoid COM
  controller_flag: True                                 # toggle on / off to set whether controller is running or not
  gravity: -9.81                                        # set gravity (my code takes this scalar and applies it along the z-axis to match Earth gravity)
  camera_azimuth: 87.5                                  # set camera azimuth 
  camera_distance: 3.                                   # set camera distance from worldbody origin
  camera_elevation: -5                                  # set camera elevation from worldbody origin; not sure why it's negative (pretend it is positive)
  camera_lookat_xyz: '0.012768, -0.000000, 1'           # configure the (x,y,z) coordinates that the camera looks at in simulation


  # Updated perturbation configuration
  apply_perturbation: False
  perturbation_type: "impulse"  # Options: "none", "impulse", "sinusoidal", "step", "random"
  
  # Impulse perturbation parameters
  perturbation_magnitude: 100
  perturbation_time: 0.3
  perturbation_period: 3.25
  perturbation_direction: null  # null for random direction, 1 or -1 for fixed direction
  
  # Sinusoidal perturbation parameters
  perturbation_amplitude: 50
  perturbation_frequency: 0.5
  perturbation_phase: 0
  
  # Step perturbation parameters
  perturbation_start_time: 5.0
  perturbation_duration: null  # null for continuous until end
  
  # Random perturbation parameters
  perturbation_max_magnitude: 100
  perturbation_min_duration: 0.2
  perturbation_max_duration: 1.0
  perturbation_min_interval: 2.0
  perturbation_max_interval: 5.0

  # New controller configuration section
  controllers:
    human:
      type: "PD"  # Set to "PD", "LQR", or "Precomputed"
      max_torque_df: 22
      max_torque_pf: -88
      mrtd_df: 148
      mrtd_pf: 389
      
      # PD parameters for ankle
      pd_params:
        kp: 100
        kd: 10
        
      # LQR parameters for ankle (if using LQR)
      lqr_params:
        Q_angle: 1000
        Q_velocity: 4000
        R: 1
    
    # Hip controller parameters
    hip:
      max_torque_ext: 150    # Maximum extension torque
      max_torque_flex: -150  # Maximum flexion torque
      
      # PD parameters for hip
      pd_params:
        kp: 50
        kd: 5
      
      # LQR parameters for hip (if using LQR)
      lqr_params:
        Q_angle: 1500
        Q_velocity: 5000
        R: 0.8
    
    # Exoskeleton controller (ankle only)
    exo:
      type: "PD"
      max_torque: 50
      pd_params:
        use_dynamic_gains: true
        kp: 400
        kd: 10
      

  