config:
  
  ankle_position_setpoint_radians: 0.0872665         # set the ankle joint setpoint in radians
  ankle_initial_position_radians:  0.0872 #0.0872665             # set the initial ankle angle in radians

  foot_angle_initial_position_radians: 0                # set the initial angle of the foot
  simend: 10                                           # set the duration for which the simulation will run
  M_total: 80                                           # total mass of the human, used for literature estimate calculations
  H_total: 1.78                                         # total height of the human, used for literature estimtae calculations
  mp4_file_name: 'pert_with_contact_force_vis.mp4'      # file name for mp4 file to be saved to, if you want to record the simultation rendering
  mp4_fps: 60                                           # video fps
  mp4_flag: False                                      # toggle this parameter on / off to save an mp4 video with name "mp4_file_name" (two lines up)
  translation_friction_constant: 0.99                   # set the translationl friction constant for model geoms
  rolling_friction_constant: 0.99                       # set the rolling friction constant for model geoms
  xml_path: 'initial_humanoid.xml'                      # set the file path that the run_sim.py script will read and modify with literature estimates
  lit_xml_file: 'literature_humanoid.xml'               # set file path that run_sim.py will save literature estimate XML file too; this is loaded into the MuJoCo backend
  plotter_flag: False                                 # toggle the Python plotters on / off
  simulation_timestep: 0.0005     #0.0001               # set the simulation timestep - this attribute is critical to simulation success
  visualization_flag: True  # Enable/disable MuJoCo 3D visualization
  visualize_contact_force: False                         # toggle on / off to visualize contact forces
  visualize_perturbation_force: False                    # toggle on / off to visualize perturbation forces
  visualize_joints: False                               # toggle on / off to visualize model joints
  visualize_actuators: False                             # toggle on / off to visualize model actuators
  visualize_center_of_mass: False                       # toggle on / off to visualize humanoid COM
  controller_flag: True                                 # toggle on / off to set whether controller is running or not
  gravity: -9.81                                        # set gravity (my code takes this scalar and applies it along the z-axis to match Earth gravity)
  camera_azimuth: 87.5                                  # set camera azimuth 
  camera_distance: 3.                                   # set camera distance from worldbody origin
  camera_elevation: -5                                  # set camera elevation from worldbody origin; not sure why it's negative (pretend it is positive)
  camera_lookat_xyz: '0.012768, -0.000000, 1'           # configure the (x,y,z) coordinates that the camera looks at in simulation


  # Updated perturbation configuration
  apply_perturbation: False
  perturbation_type: "impulse"  # Options: "none", "impulse", "sinusoidal", "step", "random"
  
  # Impulse perturbation parameters
  perturbation_magnitude: 100
  perturbation_time: 0.3
  perturbation_period: 3.25
  perturbation_direction: null  # null for random direction, 1 or -1 for fixed direction
  
  # Sinusoidal perturbation parameters
  perturbation_amplitude: 50
  perturbation_frequency: 0.5
  perturbation_phase: 0
  
  # Step perturbation parameters
  perturbation_start_time: 5.0
  perturbation_duration: null  # null for continuous until end
  
  # Random perturbation parameters
  perturbation_max_magnitude: 100
  perturbation_min_duration: 0.2
  perturbation_max_duration: 1.0
  perturbation_min_interval: 2.0
  perturbation_max_interval: 5.0

  # New controller configuration section
  controllers:
    human:
      type: "LQR"  # Options: "LQR", "PD"
      max_torque_df: 43    # Maximum dorsiflexion torque (Nm)
      max_torque_pf: -181  # Maximum plantarflexion torque (Nm)
      mrtd_df: 309        # Maximum rate of torque development for dorsiflexion (Nm/s)
      mrtd_pf: 957        # Maximum rate of torque development for plantarflexion (Nm/s)
      
      # LQR specific parameters
      lqr_params:
        Q_angle: 2000     # State cost for angle
        Q_velocity: 400   # State cost for velocity
        R: 0.01          # Control cost
      
      # PD specific parameters
      pd_params:
        kp: 100          # Proportional gain
        kd: 10           # Derivative gain
    
    exo:
      type: "None"         # Options: "PD", "None" 
      max_torque: 50     # Maximum exo torque (Nm)
      
      # PD specific parameters
      pd_params:
        kp: 400           # Proportional gain
        kd: 10            # Derivative gain
      

  