config:
  
  ankle_position_setpoint_radians: 0.0       # set the ankle joint setpoint in radians
  ankle_initial_position_radians:  -0.00 #0.0872665             # set the initial ankle angle in radians

  # # Initial velocities
  foot_rotation_initial_velocity: 0.0
  foot_x_initial_velocity: 0.0
  foot_z_initial_velocity: 0.0
  ankle_initial_velocity: 0.0  # Example: Set initial ankle velocity to 0.2 rad/s

  # Add these new parameters for hip joint
  hip_position_setpoint_radians: 0.0      # set the hip joint setpoint in radians
  hip_initial_position_radians: 0.5       # set the initial hip angle in radians
  hip_initial_velocity: -0.3               # set the initial hip angular velocity in rad/s

  foot_angle_initial_position_radians: 0                # set the initial angle of the foot
  simend: 5                                           # set the duration for which the simulation will run
  M_total: 60                                           # total mass of the human, used for literature estimate calculations
  H_total: 1.59                                         # total height of the human, used for literature estimtae calculations
  mp4_file_name: 'LQR_PDexo_unbalance.mp4'      # file name for mp4 file to be saved to, if you want to record the simultation rendering
  mp4_fps: 60                                           # video fps
  mp4_flag: True                                      # toggle this parameter on / off to save an mp4 video with name "mp4_file_name" (two lines up)
  translation_friction_constant: 0.99                   # set the translationl friction constant for model geoms
  rolling_friction_constant: 0.99                       # set the rolling friction constant for model geoms
  xml_path: 'initial_humanoid.xml'                      # set the file path that the run_sim.py script will read and modify with literature estimates
  lit_xml_file: 'literature_humanoid.xml'               # set file path that run_sim.py will save literature estimate XML file too; this is loaded into the MuJoCo backend
  plotter_flag: True                                 # toggle the Python plotters on / off
  simulation_timestep: 0.0005     #0.0001               # set the simulation timestep - this attribute is critical to simulation success
  visualization_flag: True  # Enable/disable MuJoCo 3D visualization
  visualize_contact_force: False                         # toggle on / off to visualize contact forces
  visualize_joints: False                              # toggle on / off to visualize model joints
  visualize_actuators: False                             # toggle on / off to visualize model actuators
  visualize_center_of_mass: False                      # toggle on / off to visualize humanoid COM
  controller_flag: True                                 # toggle on / off to set whether controller is running or not
  gravity: -9.81                                        # set gravity (my code takes this scalar and applies it along the z-axis to match Earth gravity)
  camera_azimuth: 87.5                                  # set camera azimuth 
  camera_distance: 3.                                   # set camera distance from worldbody origin
  camera_elevation: -5                                  # set camera elevation from worldbody origin; not sure why it's negative (pretend it is positive)
  camera_lookat_xyz: '0.012768, -0.000000, 1'           # configure the (x,y,z) coordinates that the camera looks at in simulation

  # New controller configuration section
  controllers:
    human:
      type: "LQR"  # Options: "LQR", "PD", "Precomputed"
      max_torque_df: 22    # Maximum dorsiflexion torque (Nm)
      max_torque_pf: -88  # Maximum plantarflexion torque (Nm)
      mrtd_df: 148        # Maximum rate of torque development for dorsiflexion (Nm/s)
      mrtd_pf: 389        # Maximum rate of torque development for plantarflexion (Nm/s)
      
      # LQR specific parameters
      lqr_params:
        Q_angle: 1000     # State cost for angle
        Q_velocity: 4000   # State cost for velocity
        R: 1          # Control cost
      
      # PD specific parameters
      pd_params:
        kp: 100          # Proportional gain
        kd: 10           # Derivative gain
    
      # PD specific parameters
      precomputed_params:
        trajectory_file: "ankle_torque_trajectory.csv"

    exo:
      type: "PD"         # Options: "PD", "None" 
      max_torque: 50     # Maximum exo torque (Nm)
      
      # PD specific parameters
      pd_params:
        use_dynamic_gains: true  # New flag to indicate we want to use calculated gains
        kp: 400           # Proportional gain
        kd: 10            # Derivative gain
    
    hip:
      type: "PD"         # PD controller for hip
      max_torque: 150    # Maximum hip torque (Nm)
      
      # PD specific parameters
      pd_params:
        kp: 700          # Proportional gain
        kd: 100           # Derivative gain

